CREATE OR ALTER VIEW [dbo].[vwMateriaPrima] AS

SELECT
	DISTINCT(TLM.GUID_LINHA) AS 'ID',
	TORC.N_ORCAMENTO AS 'Nº Orçamento',
	TOS.N_OS AS 'Serviço',
	TLM.COD_OS_COMPLETO AS 'OS',
	TOSA.SUBTITULO AS 'Título',
	CASE
		WHEN (TLM.RESERVADO = 1 OR TLM.QTDE_RESERVADA <> 0) THEN 1
		ELSE 0
	END AS 'Uso de Estoque',
	TSOL.COD_SOLICITACAO AS 'Cód. de Solicitação',
	CASE
		WHEN TCOTA.COD_COTACAO IS NOT NULL THEN TCOTA.COD_COTACAO
		ELSE CASE
				WHEN TCOT.GERADO_ORDEM_COMPRA = 0 THEN NULL
				ELSE TCOT.CODIGO
			END
	END AS 'Cód. de Cotação',
	TORD.COD_ORD_COMPRA AS 'OC',
	TORDC.ENVIADO_FORNECEDOR AS 'Enviado ao Fornecedor',
	TCOMP.CODIGO AS 'Cód. Entrada',
	TCOMP.N_NF AS 'NF',
	TORD.PLANO_CONTAS AS 'Plano de Contas',
	TLM.COD_INTERNO AS 'Cód. Interno do Produto',
	TLM.PRODUTO AS 'Produto',
	TORDC.FORNECEDOR AS 'Fornecedor',
	TORC.CLIENTE AS 'Cliente',
	CONVERT(DATE, TSOL.DT_SOLICITACAO) AS 'Data de Solicitação',
	CONVERT(DATE, TSOL.DT_NECESSIDADE) AS 'Data de Necessidade',
	CONVERT(DATE, TSOL.DT_PREVISTA_ENTREGA) AS 'Data Prevista de Entrega',
	CONVERT(DATE, TCOMP.DT_RECEBIMENTO) AS 'Data de Entrega',
	TSOL.QTDE_COMPROMETIDA AS 'Qtd. Reservada',
	TSOL.QTDE AS 'Qtd. Solicitada',
	TCOMOS.QTDE AS 'Qtd. Comprada',
	TCOM.QTDE AS 'Qtd. Entregue',
	TLM.UNIDADE_COMPRA AS 'Unidade',
	CASE
		WHEN (TSOL.QTDE = 0 AND TSOL.COD_SOLICITACAO IS NULL AND TLM.RESERVADO = 1) THEN '99- Retirado do Estoque'
		WHEN (TCOMP.DT_RECEBIMENTO IS NOT NULL) THEN '06- Entregue'
		WHEN (TCOMP.CODIGO IS NOT NULL) THEN '06- Entregue'
		WHEN (TSOL.DT_PREVISTA_ENTREGA < GETDATE() AND TSOL.DT_PREVISTA_ENTREGA IS NOT NULL) THEN '01- Atrasado'
		WHEN (TORD.COD_ORD_COMPRA IS NOT NULL) THEN '05- Ag. Entrega'
		WHEN (TCOTA.COD_COTACAO IS NOT NULL) THEN '04- Cotado'
		WHEN (TSOL.COD_SOLICITACAO IS NOT NULL) THEN '03- Solicitado'
		ELSE '02- Não Solicitado'
	END AS 'Status da Entrega'
FROM
	TLIS_MAT AS TLM

--Serviços e Orçamentos
INNER JOIN (SELECT COD_OS, CODIGO, COD_OS_COMPLETO, SUBTITULO FROM TOS_AUX WHERE STATUS IN ('EM ABERTO', 'EM PRODUÇÃO', 'CONCLUÍDO', 'RETRABALHO')) AS TOSA
	ON TLM.COD_OS = TOSA.COD_OS AND TLM.COD_OS_AUX = TOSA.CODIGO AND TLM.COD_OS_COMPLETO = TOSA.COD_OS_COMPLETO
		INNER JOIN (SELECT CODIGO, GUID_ORCAMENTO, N_OS FROM TOS WHERE N_OS <> 1 AND APROVADO = 1 AND CANCELADO = 0 AND N_OS NOT LIKE 'E%') AS TOS
			ON TOSA.COD_OS = TOS.CODIGO
				INNER JOIN (SELECT GUID_LINHA, COD_ORCAMENTO FROM TORCAMENTO_ITENS) AS TORCI
					ON TOS.GUID_ORCAMENTO = TORCI.GUID_LINHA
						INNER JOIN (SELECT CODIGO, N_ORCAMENTO, CLIENTE FROM TORCAMENTO) AS TORC
							ON TORCI.COD_ORCAMENTO = TORC.CODIGO

--Solicitações
LEFT JOIN (SELECT GUID_LM, GUID_PAI FROM TSOL_MAX_OS WHERE COD_OS <> 1 AND CANCELADO = 0) AS TSOLOS
	ON TLM.GUID_LINHA = TSOLOS.GUID_LM
		LEFT JOIN (SELECT GUID_LINHA, COD_SOLICITACAO, DT_SOLICITACAO, DT_NECESSIDADE, DT_PREVISTA_ENTREGA, QTDE_COMPROMETIDA, QTDE FROM TSOL_MAX WHERE SITUACAO <> 'RECUSADO') AS TSOL
			ON TSOLOS.GUID_PAI = TSOL.GUID_LINHA

--Cotações	
LEFT JOIN (SELECT GUID_LM, GUID_PAI FROM TCOT_AUX_OS WHERE COD_OS <> 1 AND CANCELADO = 0) AS TCOTOS
	ON TLM.GUID_LINHA = TCOTOS.GUID_LM
		LEFT JOIN (SELECT GUID_LINHA, COD_COTACAO FROM TCOT_AUX) AS TCOTA
			ON TCOTOS.GUID_PAI = TCOTA.GUID_LINHA
				LEFT JOIN (SELECT * FROM TCOTACAO) AS TCOT
					ON TCOTA.COD_COTACAO = TCOT.CODIGO
						LEFT JOIN (SELECT * FROM TCOT_FOR) AS TCOTF
							ON TCOT.CODIGO = TCOTF.COD_COTACAO

--Compras
LEFT JOIN (SELECT GUID_LM, GUID_PAI, COD_COTACAO FROM TORD_AUX_OS WHERE COD_OS <> 1 AND CANCELADO = 0) AS TORDOS
	ON TLM.GUID_LINHA = TORDOS.GUID_LM
		LEFT JOIN (SELECT GUID_LINHA, COD_ORD_COMPRA, PLANO_CONTAS FROM TORD_AUX) AS TORD
			ON TORDOS.GUID_PAI = TORD.GUID_LINHA
				LEFT JOIN (SELECT CODIGO, ENVIADO_FORNECEDOR, FORNECEDOR FROM TORD_COM) AS TORDC
					ON TORD.COD_ORD_COMPRA = TORDC.CODIGO

--Estoque
LEFT JOIN (SELECT GUID_LM, GUID_PAI, QTDE FROM TCOM_AUX_OS WHERE COD_OS <> 1 AND CANCELADO = 0) AS TCOMOS
	ON TLM.GUID_LINHA = TCOMOS.GUID_LM
		LEFT JOIN (SELECT GUID_LINHA, REALCIONA_AUTO, QTDE FROM TCOM_AUX) AS TCOM
			ON TCOMOS.GUID_PAI = TCOM.GUID_LINHA
				LEFT JOIN (SELECT CODIGO, N_NF, DT_RECEBIMENTO FROM TCOMPRAS) AS TCOMP
					ON TCOM.REALCIONA_AUTO = TCOMP.CODIGO

GO


